Repository sonofmath/MultiThreadingExtravaganza, pull requests merged in 2019-12, with the labels that each got.

#4 Testing PR
  README.md
Labels: documentation

#1 Setup initial directory structure
  docs/placeholder.md
  scr/C++/__tests__/test.cpp
  scr/C++/placeholder.cpp
  scripts/danger.js
Labels: structural

#5 added C pthread examples
  C/pthreads/multipleThreads/Makefile
  C/pthreads/multipleThreads/multThreads.c
  C/pthreads/pthreadSingleGlobalVar/Makefile
  C/pthreads/pthreadSingleGlobalVar/threadGlobalVar.c
Labels: enhancement
